---
title: "cover_ggseg"
author: "Athanasia Monika Mowinckel & Didac Vidan Piñeiro"
date: "12/18/2019"
output: pdf_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = TRUE)
```

Dear editor,

we would like for you to consider our manuscipt *Visualisation of Brain Statistics with R-packages _ggseg_ and _ggseg3d_* for publication in your journal *Advances in Methods and Practices in Psychological Science*. This tutorial walks the reader through the basic principles in our two R-packages for data visualization of brain segmentation data directly through R. As neuroimaging data have innate spatial information, it is crucial to keep this information when disseminating results, but it can be cumbersome for researchers to change between statistical and neuroimaging software. Our packages offer two solutions for visualizing results based on brain segmentations, one using 2D polygons and the other using 3D meshes. We believe these tool conform to the essence of open science, and invite users to improve the code, provide examples, or tutorials, and contribute to the atlas collection according to their own interest and needs. Furthermore, these packages integrate with other R tools, like Rmarkdown and shiny, creating streamlined, transparent, and reproducible ways to create dissemination reports. 

We believe this tutorial is of interest to your subscribers and fits well with the journal scope, and hope you will consider it for review and publication.

All the best,

Athanasia Monika Mowinckel,

_Staff scientist_
_Center for Lifespan Changes in Brain and Cognition_
_Dept. of Psychology_
_University of Oslo_
_Norway_


