---
title: Visualisation of Brain Statistics with R-package ggseg
author:
  - name: Athanasia M. Mowinckel
    affiliation: Center for Lifespan Changes in Brain and Cognition, Univeristy of Oslo
    address:
    - Postboks 1094 Blindern
    - 0317 Oslo
    - Norway
    email:  a.m.mowinckel@psykologi.uio.bo
  - name: Didac Vidal Piñeiro
    affiliation: Center for Lifespan Changes in Brain and Cognition, Univeristy of Oslo
    address:
    - Postboks 1094 Blindern
    - 0317 Oslo
    - Norway
    email:  d.v.pineiro@psykologi.uio.no
abstract: >
  (150 words) An abstract of less than 150 words.
output:
  rticles::rjournal_article:
    includes:
      in_header: preamble.tex
---

## Introduction

Neuroscientific analysis usually requires the use of multiple softwares to analyse, visualise, and summarise data. 
This often makes the process of preparing results for publication laborious, as results must be exported and imported in various formats. 
In neuroimaging, images of probands brain as collected and merged together to provide three dimensional representations.
Much of the neuroimaging analyses done are done not on the individal voxel (i.e. 3-dimentional pixels of brain images) level, but rather on pre-defined brain segmentations, called brain atlases.
These brain atlases are plentiful and are different ways of segmenting the brain into functionally or structurally similar regions, and the use of these is wide-spread, as these atlases provide larger meaningful divisions of the brain. 
While neuroimaging analyses on the voxel-level are usually computed by special software for such analyses, analyses of brain atlas data is usually done in standard statistical software, like R \citep{R}. 

A key part of understanding and disseminating analysis results, is the visualiasion of these in a meaningful way. 
With regards to results from brain atlas analyses, it is most meaningfully represented if projected onto a representation of the brain, rather than other standard types of charts. 
Each atlas has its own labelling depending on what is meaningful for the type of segmentation it is based on, and as such for the reader to fully understand a bar chart with atlas labels, they need to be very familiar with the location of each label to create a clear comprehension of the results.
A projection directly onto a brain shape, eases the readability of the results for the reader, and provides clear references even if the used atlas is unfamiliar. 

While there are several tools that aid R-users in plotting neuroimaging data directly through R using the grammar of graphics as implemented in ggplot2(REF), such as ggBrain(REF) and ggneuro(REF)(see [neuroconductor](https://neuroconductor.org/) for compiled neuroimaging packages for R), these are based on plotting imaging files, not results from analyses of brain atlases. 
We here introduce the ggseg-package for visualising results from brain atlas analyses.
The ggseg-package was developed to create templates that others might use to project their brain atlas results on to. 
It is based on the grammar of graphics of ggplot2 using polygons, and while its plotting functions are the what users are drawn to, it is the pre-compiled number of datasets for different brain atlases that provides the real functionality needed for visualisation of brain atlas results.


## Rationale

## Brain atlas selection
dkt, jhu, glasser, yeo7, yeo17, aseg, mid sagittal.

## ggseg3d - the plotly surface plot


## Just keep this in for now, so we remember to check
This file is only a basic article template. For full details of _The R Journal_ style and information on how to prepare your article for submission, see the [Instructions for Authors](https://journal.r-project.org/share/author-guide.pdf).
\bibliography{RJreferences}
